programs_to_terminate = ["NimdowStatus"]

[window]
width = 600
height = 98
title = "nlogout" #Can be used to set floating mode with your WM
background_color = "#f5e0dc" #System Themes Override This

[font]
family = "Iosevka NFM" #Set you button text font,
size = 16
color = "#363a4f"

[button]
width = 80
height = 80
padding = 3 #spacing around each button

[buttons.cancel]
text = "Cancel"
icon = "\uF00D" #set icon, nerd fonts or awesome font
shortcut = "Escape"
background_color = "#f5e0dc"

[buttons.logout]
text = "Logout"
icon = "\uF2F5"
shortcut = "L"
background_color = "#cba6f7"

[buttons.reboot]
text = "Reboot"
icon = "\uF021"
shortcut = "R"
background_color = "#f5c2e7"

[buttons.shutdown]
text = "Shutdown"
icon = "\uF011"
shortcut = "S"
background_color = "#f5a97f"

[buttons.suspend]
text = "Suspend"
icon = "\uF186"
shortcut = "U"
background_color = "#7dc4e4"

[buttons.hibernate]
text = "Hibernate"
icon = "\uF0E2"
shortcut = "H"
background_color = "#a6da95"

[buttons.lock]
text = "Lock"
icon = "\uF023"
shortcut = "K"
background_color = "#8aadf4"
