[window]
width = 740
height = 110
title = "nlogout"
background_color = "#ee99a0"

[font]
family = "DejaVuSans"
size = 16
color = "#363a4f"  # Add this line for the font color

[button]
width = 100
height = 100
padding = 5

[buttons.cancel]
text = "Cancel"
icon = "\uF00D"
shortcut = "Escape"
background_color = "#f5e0dc"

[buttons.logout]
text = "Logout"
icon = "\uF2F5"
shortcut = "L"
background_color = "#cba6f7"

[buttons.reboot]
text = "Reboot"
icon = "\uF021"
shortcut = "R"
background_color = "#f5c2e7"

[buttons.shutdown]
text = "Shutdown"
icon = "\uF011"
shortcut = "S"
background_color = "#f5a97f"

[buttons.suspend]
text = "Suspend"
icon = "\uF186"
shortcut = "U"
background_color = "#7dc4e4"

[buttons.hibernate]
text = "Hibernate"
icon = "\uF0E2"
shortcut = "H"
background_color = "#a6da95"

[buttons.lock]
text = "Lock"
icon = "\uF023"
shortcut = "K"
background_color = "#8aadf4"

programs_to_terminate = ["NimdowStatus"]
